export const STAFFS_LOADING = 'STAFFS_LOADING';
export const  STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_STAFFS = 'ADD_STAFFS'; 
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const ADD_SALARY = 'ADD_SALARY';
export const SALARY_FAILED = 'SALARY_FAILED';
export const STAFFS_FATCH = 'STAFFS_FATCH';
